<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TechJobsNL.Runtime</AssemblyName>
    <RootNamespace>TechJobsNL.Runtime</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Tomlyn" />
    <ProjectReference Include="../TechJobsNL.Adapters.AiExperience.DeepSeek/TechJobsNL.Adapters.AiExperience.DeepSeek.csproj" />
    <ProjectReference Include="../TechJobsNL.Adapters.Analytics.Local/TechJobsNL.Adapters.Analytics.Local.csproj" />
    <ProjectReference Include="../TechJobsNL.Adapters.Platform/TechJobsNL.Adapters.Platform.csproj" />
    <ProjectReference Include="../TechJobsNL.Adapters.Providers/TechJobsNL.Adapters.Providers.csproj" />
    <ProjectReference Include="../TechJobsNL.Core/TechJobsNL.Core.csproj" />
    <ProjectReference Include="../TechJobsNL.Persistence.Sqlite/TechJobsNL.Persistence.Sqlite.csproj" />
  </ItemGroup>
</Project>
