<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TechJobsNL.Runtime</AssemblyName>
    <RootNamespace>TechJobsNL.Runtime</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../archive/rust/config.toml" LogicalName="TechJobsNL.DefaultConfiguration.toml" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Tomlyn" />
    <ProjectReference Include="../TechJobsNL.Adapters.Providers/TechJobsNL.Adapters.Providers.csproj" />
    <ProjectReference Include="../TechJobsNL.Core/TechJobsNL.Core.csproj" />
    <ProjectReference Include="../TechJobsNL.Persistence.Sqlite/TechJobsNL.Persistence.Sqlite.csproj" />
  </ItemGroup>
</Project>
