<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="AutoFixture" Version="4.18.1" />
    <PackageVersion Include="Dapper" Version="2.1.66" />
    <PackageVersion Include="FluentAssertions" Version="7.2.0" />
    <PackageVersion Include="Meziantou.Analyzer" Version="2.0.198" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Polly.Extensions" Version="8.6.5" />
    <PackageVersion Include="Refit.HttpClientFactory" Version="9.0.2" />
    <PackageVersion Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.13" />
    <PackageVersion Include="Verify.XunitV3" Version="32.0.0" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
