<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TechJobsNL.Adapters.Analytics.Local</AssemblyName>
    <RootNamespace>TechJobsNL.Adapters.Analytics.Local</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TechJobsNL.Core/TechJobsNL.Core.csproj" />
  </ItemGroup>
</Project>
